# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '*/30 * * * *'  # 定时调度
  workflow_dispatch:  # Action ui 界面可触发 下面可描述参数


jobs:
  deploy-site:
    runs-on: ["ubuntu-latest"]
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: '.' #运行路径
    steps:
      - name: ( 1/4 ) setup environment for git
        uses: actions/checkout@v3

      - name: ( 2/4 ) cache node_modules  # ref: https://dev.to/mattpocockuk/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: ( 3/4 ) build web site
        run: cd src && npm i -g pnpm && pnpm i && pnpm fetchUpstream && pnpm build
      
      - name: ( 4/4 ) deploy web site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.Token }}
          publish_dir: ./dist

          
